company_name:
  type: string
  description: "The official name of the shipping company, carrier, or shipping line."

bl_number:
  type: string
  description: "The unique Bill of Lading (B/L) tracking number or document reference."

shipper:
  type: string
  description: "The name of the shipper, consignor, or the party sending the goods."

port_of_loading:
  type: string
  description: "The specific name or location of the port where the cargo is loaded onto the vessel."

port_of_discharge:
  type: string
  description: "The specific name or location of the port where the cargo is discharged or unloaded."

place_of_acceptance:
  type: string
  description: "The location or facility where the carrier takes initial receipt or acceptance of the cargo."

place_of_delivery:
  type: string
  description: "The final destination or location where the cargo is delivered to the consignee."

shipped_on_board_date:
  type: string
  description: "The date when the cargo was officially loaded on board the vessel. Extract the exact date string."

vessel_name:
  type: string
  description: "The name of the ship or vessel carrying the cargo."

voyage_number:
  type: string
  description: "The specific identification number or code of the vessel's voyage."

mark:
  type: string
  description: "The shipping mark : often document start, logo-like. It can be a logo, a symbol. Extract the exact string."

container_numbers:
  type: list
  description: "A list of container identification numbers associated with the shipment. Must be 4 letters followed by 7 digits (like MRKU7061784). Ensure each item is extracted separately."

lots:
  type: list
  description: "A list of description of the contained lots in the shipment per containers."
